### ISSUE TITLE
Template website

### ISSUE THREAD

**Issue by lcpojr** [lcpojr/sbg-rj#15]
Inspiração -> http://sbg-mg.org.br/

Precisamos selecionar o template que utilizaremos na página institucional.
O mesmo poderá ser um template gratuito sem fins lucrativos para que ganhemos tempo de desenvolvimento.

Sugiro que adicionemos os melhores aqui com o passar do tempo até termos o projeto mais adiantado.

**Comment by lcpojr** [comment]
Alguns templates bacanas que encontrei por ai ...

- https://themefisher.com/products/fame-free-html-website-template/
- https://themefisher.com/products/blue-free-onepage-responsive-corporate-template/
- https://themefisher.com/products/education-template/
- https://themefisher.com/products/airspace-free-bootstrap-website-template/

Outros exemplos em : https://colorlib.com/wp/templates/

**Comment by pedrocecchetti** [comment]
http://demo.themefisher.com/themefisher/blue/

Gostei muito desse.

**Comment by lcpojr** [comment]
Boa, to sabendo hahaha.
Não precisa necessariamente ser algo como esse template, mas temos q pensar em quais funcionalidades queremos colher.
Podemos simplificar algumas coisas conforme formos implementando.

**Comment by pedrocecchetti** [comment]
https://bootstrapmade.com/demo/Reveal/

Achei esse que tem alguns elementos mas é menos modernoso.

**Comment by pedrocecchetti** [comment]
Sobre os templates, conversei com a minha amiga e cheguei em algumas informações com ela sobre as paginas:

- *Landing Page*: Ver se da para atualizar o carrossel de início com as fotos Específicas de Eventos  
- *NAVBAR*: Criar aba eventos separado de SBG-RJ, criar a aba Parceirias 
- *Eventos*: 
    - É possível criar um layout de calendário com os Eventos futuros só com título e na data especificada do calendário?
        - Caso seja possível precisamos criar um outro model de Evento futuro, apenas com nome e com data?
- *Email*: É possivel criar um email com @sbg-rj hospedado no gmail?
    - Sobre isso falei com ela que é mais complexo e que seria "direto com o Google" confere?
- *Publicações*: Ela pediu para adicionarmos mais uma categoria, clippings.
-*Referências*: Podemos remover essa aba por completo. Não precisamos de nenhuma informação na parte referências.
-*Parceirias:* - Tayla vai enviar as informações dos parceiros para adicionar na aba Parceirias
-*Fotos*: -  Manter como sugerimos

**Comment by lcpojr** [comment]
Boa, tudo ali é possível.

>     * **Landing Page**: Ver se da para atualizar o carrossel de início com as fotos Específicas de Eventos.
> 

**R:** Podemos adicionar apenas um campo `slideshow` do tipo:

```python
# Home page slider
slideshow = models.BooleanField(
     default=False, 
     verbose_name="Slideshow", 
     help_text="Seleciona se a foto deve ser exibida ou não na homepage.",
)
```

> NAVBAR: Criar aba eventos separado de SBG-RJ, criar a aba Parceirias
>

**R:** Show de bola, isso é bastante simples.

> Eventos: É possível criar um layout de calendário com os Eventos futuros só com título e na data especificada do calendário? Caso seja possível precisamos criar um outro model de Evento futuro, apenas com nome e com data?
>

**R:** É perfeitamente possível, até bastante simples na verdade, com javascript. Apenas precisamos de um plugin de calendário aonde passaremos os dados do banco para o javascript com os eventos.
O evento já possuí dois campos que permitem a criação de eventos futuros, sendo eles:

```python
# Activity period
starts_at = models.DateTimeField(verbose_name="Data de início")
ends_at = models.DateTimeField(verbose_name="Data de término")
```

> Email: É possivel criar um email com @sbg-rj hospedado no gmail? Sobre isso falei com ela que é mais complexo e que seria "direto com o Google" confere?
>

**R:** Sim. O google oferece serviço de email, bastando apenas que ela seja dona de um domínio próprio. Podemos fazer essa configuração para ela se for o caso.

> Referências: Podemos remover essa aba por completo. Não precisamos de nenhuma informação na parte referências.
> 

**R:** Maravilha. Economizamos algum tempo com isso.

> Parceirias: - Tayla vai enviar as informações dos parceiros para adicionar na aba Parceirias
>

**R:** O quanto antes melhor !

> Fotos: - Manter como sugerimos
> 

**R:** Combinado !

> ID Visual: Ela disse que vai me enviar os códigos das cores da SBG pra gente ter mais facilidade
>

**R:** Show de bola.

**Comment by lcpojr** [comment]
> https://bootstrapmade.com/demo/Reveal/
> 
> Achei esse que tem alguns elementos mas é menos modernoso.

Acho esse o melhor por enquanto, podemos começar a atacar com ele.
