### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by lcpojr** [lcpojr/sbg-rj#25]
Precisamos criar uma home page bastante "clean" que contém links de acesso as demais informações.
A home page deverá conter:

- Imagem ou Slideshow explicativo;
- Resumo sobre o SBG;
- Últimos eventos;
- Ultimas publicações;
- Parceiros;
- Informações de contato;

Discussão inicial [aqui](https://github.com/lcpojr/sbg-rj/issues/15).

**Comment by lcpojr** [comment]
@pedrocecchetti estou pensando se realmente é necessário termos as ultimas publicações na home page já que esta é uma informação bem centralizada e teremos uma página apenas com isso com link ali encima.

**Comment by pedrocecchetti** [comment]
Fala Luiz, desculpa a demora. 

Realmente tb não vejo como necessário. Acho que podemos deixar o Link la em cima, pq senão daquia  pouco a página vai ficar floodada de info.

**Comment by lcpojr** [comment]
Falta adicionar os links das notícias e eventos na home page, bem como colocar `titles` e `alts`.
