### ISSUE TITLE
DB Modeling

### ISSUE THREAD

**Issue by pedrocecchetti** [lcpojr/sbg-rj#5]
Sobre a modelagem do Banco, cheguei a algumas classes que acho importantes. 
Vou analisando de página em página para poder disponibilizar as informações de forma organizada.

## [Landing Page:](http://sbg-mg.org.br/)
Na landing page temos diversas classes que serão explicitadas mais pra frente e que alterarão de acordo com o que for sendo cadastrado pelo admin:
- Eventos
- Notícias
Acho que o resto da página pode ser estático sem problemas

## [Institucional](http://sbg-mg.org.br/institutucional):
Aqui a maior parte é estática, e os textos serão disponibilizados para a gente. 
Os elementos das diretorias são bastante importantes de serem atualizados a cada 2 anos, portanto pensei nesses dois:

### Diretores:
- Cargo
- Nome
- Email

### Diretoria Bienio:
- Biênio
- Lista de diretores do Biênio

Sobre os itens acima, fiquei com um pouco de dificuldade de saber se podemos colocar um campo Biênio na classe de diretores, para puxarmos referencia ao biênio. 

## [Eventos](http://sbg-mg.org.br/eventos):
Nessa pagina temos o resumo dos eventos, mas ao acessar os detalhes do evento consegui um detalhamento melhor das informações relevantes:

### Evento:
- Título
- Data do evento
- Descrição do Evento
- Imagem Ícone
- Link para Inscrição(Isso não existe, mas é sugestão minha)
- Link para download de Apresentações.
- Imagem de Divulgação do Evento

## [Notícias](http://sbg-mg.org.br/noticias):
A mesma análise feita para evento:

### Noticias:
- Título
- Data da publicação
- Corpo da Notícia
- Imagem Ícone
- Imagem para a Notícia(SBG-MG é a mesma imagem de ícone, mas a resolução fica péssima)
- Link para a FONTE

## [Produtos](http://sbg-mg.org.br/produtos):
Os produtos só são anunciados na página os pedidos provavelmente são feitos pelo formulário abaixo:

### Produtos:
- Nome do Produto
- Imagem do Produto
- Preço Associado
- Preço Não Associado

## [Publicacoes](http://sbg-mg.org.br/publicacoes):
Dentro das publicacoes existem diversos tipos, mas pelo que entendi apenas 2 são necessários de alteração. Que são os Anais e Boletins. Para mim parece que a aba de referências pode ser totalmente estática e  Sigep-MG também,posso confirmar com ela.
Como os anais e os boletins são muito parecidos, classifiquei como publicações e seria possível escolher um tipo.

### Publicacoes:
- Nome
- Categoria(Anais de simpósio, Anais de Congresso, Boletins)
- Link para download do PDF.

## [Fotos](http://sbg-mg.org.br/fotos/)
Acho que essa seria a última página modificável, acho que as seguintes podem ser estáticas.

### Fotos:
- Título da foto
- Imagem

**Comment by lcpojr** [comment]
Boa cara, ficou bem descritivo.
Só fiquei com uma dúvida. O que seria "Bienio" ?
Se for relacionado ao período vigente em que a diretoria ficará podemos ter as informações no próprios diretor.

**Comment by pedrocecchetti** [comment]
Acho Válido a ideia de botar o Biênio como um atributo do Diretor.

- Acredito que os links de PDF e apresentação podem existir, mas é bem mais útil nós fazermos upload dos arquivos para a página.
    - Acho super válido, acaba sendo um gap técnico que tenho, mas concordo que devemos uploadear na página mesmo.
- As fotos devem trabalhar com conceito de álbum aonde temos um titulo, descrição e várias imagens.
    - Maneiro, vou adicionar na parte de fotos, o Album.
- Gostei da ideia inscrição, só temos que pensar se esses campos devem ser estáticos ou dinâmicos.
    - Sobre essa ideia, tinha pensado em direcionar para o site em que a inscrição realmente fosse ocorrer. Mas podemos sim pensar em um form de inscrição


Pergunta: Edito a issue mesmo alterando esses pontos que comentamos ou devo adicionar como comentário? No caso me parece que é uma pergunta idiota, mas pergunto mesmo assim ahahahahaha

**Comment by lcpojr** [comment]
Abri um PR relacionado a modelagem dessa issue @pedrocecchetti .

https://github.com/lcpojr/sbg-rj/pull/6

**Comment by lcpojr** [comment]
@pedrocecchetti depois de dar 1 review no modelo de imagens acima pode fechar essa issue se não tiver nenhuma dúvida.

**Comment by lcpojr** [comment]
> Acho Válido a ideia de botar o Biênio como um atributo do Diretor.
> 
>     * Acredito que os links de PDF e apresentação podem existir, mas é bem mais útil nós fazermos upload dos arquivos para a página.
>       
>       * Acho super válido, acaba sendo um gap técnico que tenho, mas concordo que devemos uploadear na página mesmo.
> 
>     * As fotos devem trabalhar com conceito de álbum aonde temos um titulo, descrição e várias imagens.
>       
>       * Maneiro, vou adicionar na parte de fotos, o Album.
> 
>     * Gostei da ideia inscrição, só temos que pensar se esses campos devem ser estáticos ou dinâmicos.
>       
>       * Sobre essa ideia, tinha pensado em direcionar para o site em que a inscrição realmente fosse ocorrer. Mas podemos sim pensar em um form de inscrição
> 
> 
> Pergunta: Edito a issue mesmo alterando esses pontos que comentamos ou devo adicionar como comentário? No caso me parece que é uma pergunta idiota, mas pergunto mesmo assim ahahahahaha

Pode deixar a discussão apenas, acho que já é suficiente para sabermos doq se trata.

**Comment by lcpojr** [comment]
@pedrocecchetti depois de dar 1 review no modelo de imagens acima pode fechar essa issue se não tiver nenhuma dúvida.
